#pragma config(Motor,  port2,            ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           drivea,        tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           driveb,        tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           drivec,        tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           drived,        tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,            ,             tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Port 3 broken, switched to port 6

void drive_left(int speed){
	motor(drivea) = speed;
	motor(drivec) = speed;
}

void drive_right(int speed){
	motor(driveb) = speed;
	motor(drived) = speed;
}

task main()
{
	while (false==false){

		drive_left(vexRT[Ch2]);
		drive_right(vexRT[Ch3]);
	}
	while (vexRT[Btn7R]==1){


 }

}
