#pragma config(Motor,  port1,           drivea,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveb,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           drivec,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           drived,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           claw_360,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw_v_axis,   tmotorVex393_MC29, openLoop)
#pragma config(Motor, port9,            intake         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          shooter,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive_left(int speed){
	motor(port1) = speed;
	motor(port2) = speed;
}
void drive_right(int speed){
	motor(port3) = speed;
  motor(port4) = speed;
}
void claw_180(int speed){//spins claw head to make the cap the coresponding color
	motor(port7) = speed;
}
void claw_vertical(int speed){//makes it where claw can go up and down
	motor(port8) = speed;
}
void ball_shooter(int speed){

	motor(port10) = speed;
}
void get_dem_balls
task main(){
	while (true){
             
              









  }
}