#pragma config(Motor,  port2,           drivea,        tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           driveb,        tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           drivec,        tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           drived,        tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           intake,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive_left(int speed){
	motor(port2)=speed;
	motor(port3)=speed;
}
void drive_right(int speed){
	motor(port4)=speed;
	motor(port5)=speed;
	motor(port6)=speed;
}

task main()
{
	while (true){

	drive_left(vexRT[Ch3]);

	drive_right(vexRT[Ch2]);




 }
}
