#pragma config(Motor,  port2,           drive,         tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor(port2) = vexRT[Ch3];



}
